### ISSUE TITLE
not working with pixelmon dark

### ISSUE THREAD

**Issue by vaniron** [superteits/PixelMoney#7]
Hello, latest build of your plugin is not working with latest pixelmon dark - https://www.technicpack.net/modpack/pixelmon-513-pro.1072839 - source should be same as latest official pixelmon - can you look at it for me please?

**Comment by PixelmonPRO** [comment]
I have this errors too.
Plugins work, but when players win Pokémon, there is a strong spam in the console...

**Comment by vaniron** [comment]
working as intended, problem was fixed by setting dimensions in config to [0, -1, 47]
